# Generated by Django 3.1.10 on 2021-05-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210525_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='main_content',
            new_name='content',
        ),
    ]
