# Generated by Django 3.1.10 on 2021-05-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home page Atlas RDV', 'verbose_name_plural': 'Accueil Page AtlasRDV'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
