# Generated by Django 3.1.10 on 2021-05-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210515_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_description',
            field=models.TextField(null=True),
        ),
    ]
