# Generated by Django 3.1.10 on 2021-05-19 13:23

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_categorieservice_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieservice',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Unique identifier', populate_from='name'),
        ),
    ]
