# Generated by Django 3.1.10 on 2021-05-20 12:49

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_extratext_footertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='extratext',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
