# Generated by Django 3.1.10 on 2021-05-20 12:52

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_extratext_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='extratext',
            name='name',
            field=models.CharField(default='Vide', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extratext',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
