# Generated by Django 3.1.10 on 2021-05-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210520_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extratext',
            name='slug',
            field=models.SlugField(),
        ),
    ]
