# Generated by Django 3.1.10 on 2021-05-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210520_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extratext',
            name='body',
            field=models.TextField(),
        ),
    ]
