# Generated by Django 3.1.10 on 2021-05-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210520_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='icon_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
