# Generated by Django 3.1.10 on 2021-05-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_servicepage_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='icon_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
