# Generated by Django 3.1.10 on 2021-05-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210520_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='icon_name',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='icon_slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
