# Generated by Django 3.1.10 on 2021-05-20 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210520_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='icon_slug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_service', to='home.extratext'),
        ),
    ]
