# Generated by Django 3.1.10 on 2021-05-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210521_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='icon_slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
