# Generated by Django 3.1.10 on 2022-02-21 16:59

from django.db import migrations
import streamfieldblocks.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_servicestremfieldpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicestremfieldpage',
            name='body',
        ),
        migrations.AddField(
            model_name='servicestremfieldpage',
            name='content',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.StructBlock([('richtext', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul']))])), ('responsive_image', streamfieldblocks.models.ResponsiveImageBlock()), ('service', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock()), ('body', wagtail.core.blocks.TextBlock()), ('page_link', wagtail.core.blocks.PageChooserBlock())]))], blank=True),
        ),
    ]
