# Generated by Django 3.1.10 on 2021-05-22 12:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliopage',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='headline_text',
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='experience',
            field=wagtail.core.fields.StreamField([('Timeline_Block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=100)), ('text', wagtail.core.blocks.TextBlock()), ('date', wagtail.core.blocks.DateBlock())]))], blank=True, null=True),
        ),
    ]
