# Generated by Django 3.1.10 on 2021-05-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('portfolio', '0002_auto_20210522_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='background_image',
            field=models.ForeignKey(help_text='Header background image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='headline_text',
            field=models.CharField(blank=True, help_text='Blog listing page header text.', max_length=70),
        ),
    ]
